DotaCastStats/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cast/', include("league_analysis.urls", namespace="cast"))
]

league_analysis/urls.py
from django.urls import path

from league_analysis import views
app_name = "casting"
urlpatterns = [
    path("live/", views.live_data, name="live"),
    path("head-to-head/", views.head_to_head, name="head-to-head"),
    path("team-select/", views.select_teams, name="team-select"),
    path("demo/", views.css_demo, name="css-demo")
]

league_analysis/models.py
from django.db import models


class Team(models.Model):
    id = models.CharField(primary_key=True, max_length=50)
    name = models.CharField(max_length=200)
    logo_image_url = models.CharField(max_length=600, default="https://i.imgur.com/JYuNKXp.jpg")

    def __str__(self):
        return self.name


class Hero(models.Model):
    id = models.CharField(max_length=10, primary_key=True)
    common_name = models.CharField(max_length=200)

    def __str__(self):
        return f"{self.common_name}({self.id})"


# TODO write class for takss like: "update all data". Run it nightly or some shit
# TODO FIGURE OUT HOW TO JAM LIVE DATA INTO THAT LIVE MATCH AUTOMATICALLY. Create a new OngoingMatch, populate it with players
# Maybe via celery?

class TeamHeroPickStatistics(models.Model):
    team = models.ForeignKey(to=Team, related_name="hero_stats", on_delete=models.DO_NOTHING)
    hero = models.ForeignKey(to=Hero, related_name="pick_stats", on_delete=models.DO_NOTHING)
    pick_count = models.IntegerField(default=0)
    win_count = models.IntegerField(default=0)
    win_percent = models.FloatField(default=0)

    def __str__(self):
        return f"[team:{self.team}, hero:{self.hero}, pick_count:{self.pick_count}, win_count:{self.win_count}, win_percent:{self.win_percent}"


class TeamRollingStatistics(models.Model):
    team = models.OneToOneField(to=Team, related_name="statistics", on_delete=models.CASCADE)
    average_kills = models.FloatField(default=0)
    average_deaths = models.FloatField(default=0)
    average_assists = models.FloatField(default=0)
    average_kda = models.FloatField(default=0)
    matches_played = models.IntegerField(default=0)
    matches_won = models.IntegerField(default=0)
    series_played = models.IntegerField(default=0)
    series_won = models.IntegerField(default=0)
    average_creep_stats = models.FloatField(default=0)
    average_xpm = models.FloatField(default=0)
    average_gpm = models.FloatField(default=0)

    def __str__(self):
        return f"[team:{self.team}," \
               f"average_kills:{self.average_kills}," \
               f"average_deaths:{self.average_deaths}," \
               f"average_assists:{self.average_assists}," \
               f"average_kda:{self.average_kda}," \
               f"average_assists:{self.matches_played}," \
               f"matches_won:{self.matches_won}," \
               f"series_played:{self.series_played}," \
               f"series_won:{self.series_won}," \
               f"average_creep_stats:{self.average_creep_stats}," \
               f"average_xpm:{self.average_xpm}," \
               f"average_gpm:{self.average_gpm}]"


class Player(models.Model):
    steam_id_64 = models.IntegerField()
    steam_id_3 = models.IntegerField()
    player_id = models.IntegerField()
    player_name = models.CharField(max_length=255)

    def __str__(self):
        return f"[player_name:{self.player_name}," \
           f"steam_id_64:{self.steam_id_64}," \
           f"steam_id_3:{self.steam_id_3}," \
           f"player_id:{self.player_id}]"


class PlayerRollingStatistics(models.Model):
    player = models.OneToOneField(to=Player, on_delete=models.CASCADE)
    average_kills = models.FloatField(default=0)
    average_deaths = models.FloatField(default=0)
    average_assists = models.FloatField(default=0)
    average_kda = models.FloatField(default=0)
    average_creep_stats = models.FloatField(default=0)
    average_xpm = models.FloatField(default=0)
    average_gpm = models.FloatField(default=0)
    most_common_role = models.CharField(blank=True, null=True, max_length=2)

    def __str__(self):
        return f"[player:{self.player}," \
           f"average_kills:{self.average_kills}," \
           f"average_deaths:{self.average_deaths}," \
           f"average_assists:{self.average_assists}," \
           f"average_kda:{self.average_kda}," \
           f"average_creep_stats:{self.average_creep_stats}," \
           f"average_xpm:{self.average_xpm}," \
           f"average_gpm:{self.average_gpm}," \
           f"most_common_role:{self.most_common_role}]"


class OngoingMatch(models.Model):
    team_one = models.ForeignKey(to=Team, related_name="matches_as_first_team", on_delete=models.DO_NOTHING)
    team_two = models.ForeignKey(to=Team, related_name="matches_as_second_team", on_delete=models.DO_NOTHING)
    team_one_players = models.ManyToManyField(to=Player, related_name="matches_on_first_team")
    team_two_players = models.ManyToManyField(to=Player, related_name="matches_on_second_team")

    def __str__(self):
        return f"[team_one:{self.team_one}," \
               f"team_two:{self.team_two}," \
               f"team_one_players:{self.team_one_players}," \
               f"team_two_players:{self.team_two_players}]"


class FinishedMatch(OngoingMatch):
    # TODO add post-stats here
    pass

league_analysis/forms.py
from django import forms

from league_analysis.models import Team


class TeamSelectForm(forms.Form):
    teams = forms.ModelMultipleChoiceField(queryset=Team.objects.all(), required=True)

league_analysis/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.template import loader
from django.urls import reverse

from league_analysis.forms import TeamSelectForm
from league_analysis.models import TeamRollingStatistics, Team
# Create your views here.

def live_data(request):
    if request.method == "GET":
        return "hi!"

def head_to_head(request):
    team_one_id = request.GET.get("team_one")
    team_two_id = request.GET.get("team_two")
    context = {
        "team_one_statistics": TeamRollingStatistics.objects.get(team__id=team_one_id),
        "team_two_statistics": TeamRollingStatistics.objects.get(team__id=team_two_id)
    }
    return render(request, "leagueanalysis/headtohead.html",context)

def css_demo(request):
    return render(request, "leagueanalysis/cssexample.html", {})

def select_teams(request):
    if request.method == "POST":
        form = TeamSelectForm(request.POST)
        if form.is_valid():
            return HttpResponseRedirect(reverse("cast:head-to-head",) + f"?team_one={form.cleaned_data['teams'][0].id}&team_two={form.cleaned_data['teams'][1].id}")
    else:
        form = TeamSelectForm()

    return render(request, "leagueanalysis/teamselection.html", {"form": form})

league_analysis/templates/leagueanalysis/cssexample.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'league_analysis/style.css' %}">
<html>
    <body>
        <ul>
            <li> wow its green!</li>
        </ul>
    </body>
</html>

league_analysis/templates/leagueanalysis/headtohead.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static '/league_analysis/style.css' %}">
<html>
<head>
    <title>WLDL Head to Head Team Analysis</title>
    <style>
        div.background_img{
            background: url("https://external-preview.redd.it/OHPkrqAG9vgxPb7HxD8NxaJ8KgFNiAaA8ftYQo0t91U.jpg?width=960&crop=smart&auto=webp&s=2dfdfc1f28b5bfda104147f4a83601565393ff0e");
            background-repeat: no-repeat;
        }
        div.table_background{
            background: rgba(0,0,0,0.6);
            width: 660px;
            height: 960px;
            margin-left: 150px;
        }
        div.stat_table {
            opacity: 1;
        }
    </style>
</head>
<body>
    <div class="background_img" align="left">
        <div class="table_background" align="left">
            <div class="stat_table"  align="center">
                <table>
                    <thead>
                        <tr>
                            <th>
                                <h2>{{ team_one_statistics.team.name }}</h2>
                            </th>
                            <th></th>
                            <th>
                                <h2>{{ team_two_statistics.team.name }}</h2>
                            </th>
                        </tr>
                        <tr>
                            <td style="opacity: 1;"><img src="{{ team_one_statistics.team.logo_image_url }}" width="200px" style="opacity: 1"/></td>
                            <th></th>
                            <td style="opacity: 1;"><img src="{{ team_two_statistics.team.logo_image_url }}" width="200px" style="opacity: 1"/></td>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td><h4>{{ team_one_statistics.series_played}}</h4></td>
                            <td><h3>series played</h3></td>
                            <td><h5>{{ team_two_statistics.series_played}}</h5></td>
                        </tr>
                        <tr>
                            <td><h4>{{ team_one_statistics.series_won}}</h4></td>
                            <td><h3>series won</h3></td>
                            <td><h5>{{ team_two_statistics.series_won}}</h5></td>
                        </tr>
                        <tr>
                            <td><h4>{{ team_one_statistics.average_kda|floatformat }}</h4></td>
                            <td><h3>Average KDA</h3></td>
                            <td><h5>{{ team_two_statistics.average_kda|floatformat}}</h5></td>
                        </tr>
                        <tr>
                            <td><h4>{{ team_one_statistics.average_kills}}</h4></td>
                            <td><h3>Average Kills</h3></td>
                            <td><h5>{{ team_two_statistics.average_kills}}</h5></td>
                        </tr>
                        <tr>
                            <td><h4>{{ team_one_statistics.average_deaths}}</h4></td>
                            <td><h3>Average Deaths</h3></td>
                            <td><h5>{{ team_two_statistics.average_deaths}}</h5></td>
                        </tr>
                        <tr>
                            <td><h4>{{ team_one_statistics.average_assists}}</h4></td>
                            <td><h3>Average Assists</h3></td>
                            <td><h5>{{ team_two_statistics.average_assists}}</h5></td>
                        </tr>
                        <tr>
                            <td><h4>{{ team_one_statistics.average_xpm}}</h4></td>
                            <td><h3>Average XPM</h3></td>
                            <td><h5>{{ team_two_statistics.average_xpm}}</h5></td>
                        </tr>
                        <tr>
                            <td><h4>{{ team_one_statistics.average_gpm}}</h4></td>
                            <td><h3>Average GPM</h3></td>
                            <td><h5>{{ team_two_statistics.average_gpm}}</h5></td>
                        </tr>
                        <tr>
                            <td><h4>{{ team_one_statistics.average_creep_stats}}</h4></td>
                            <td><h3>Average Creep Score</h3></td>
                            <td><h5>{{ team_two_statistics.average_creep_stats}}</h5></td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</body>
</html>

league_analysis/templates/leagueanalysis/teamselection.html
<html>
<body>
<form action="{% url 'cast:team-select' %}" method="post">
    {% csrf_token %}
    {{ form }}
     <input type="submit" value="Submit">
</form>

</body>
</html>